{%set name = "ua-parser" %}
{% set version = "0.9.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{% set hash_val = "be17242abcd4f3d11543e9b82826f152b47c724623a32bb94ce02e549b0cfce2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - pyyaml

  run:
    - python

test:
  imports:
    - ua_parser

about:
  home: https://github.com/ua-parser/uap-python
  license: Apache 2.0
  license_family: Apache
  summary: "Python port of Browserscope's user agent parser"
  dev_url: https://github.com/ua-parser/uap-python

extra:
  recipe-maintainers:
    - pmlandwehr
