{% set name = "ua-parser" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ua_parser-{{ version }}.tar.gz
  sha256: a9740f53f4fbb72b7a03d304cae32a2785cafc55e8207efb74877bba17c35324

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
    - pyyaml
  run:
    - python >={{ python_min }}
    - ua-parser-builtins

test:
  imports:
    - ua_parser
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ua-parser/uap-python
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Python port of Browserscope's user agent parser
  dev_url: https://github.com/ua-parser/uap-python

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
